### ISSUE TITLE
Weitere Informationen ins HTML

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/COVID-19-NRW#2]
Ich finde der Seite sollte folgendes noch hinzugefügt werden:

- Link zum Download der Rohdaten hier im Repository
- Erklärung zur Datenlizenz (Gibts da eine ?)
- Link zu diesem Repository
- Link zu anderen Ländern

@silberzwiebel kannst du was zu der Datenlizenz sagen?

**Comment by silberzwiebel** [comment]
So, alles etwas umstrukturiert und dafür werden nun die Daten aus dem Open-Data-Portal genutzt: https://opendata.stadt-muenster.de/dataset/coronavirus-infektionen-sars-cov-2-im-regierungsbezirk-m%C3%BCnster

Was meinst Du mit "Link zu anderen Ländern"? Bundesländer? Oder Nationen? Es gibt sehr viele Dashboards, bin mir grad nicht sicher, was da sinnvoll wäre ...

**Comment by ubergesundheit** [comment]
Stark!

Dachte primär an das [COVID-19-NDS repo von code for osnabrück](https://github.com/codeforosnabrueck/COVID-19-NDS), also Länder = Bundesländer, aber du hast wohl recht, wahrscheinlich ein bisschen viel..
