### ISSUE TITLE
Feature: Skala logaritmisch und mit Wachstumsrate

### ISSUE THREAD

**Issue by sandzwerg** [codeformuenster/COVID-19-NRW#4]
Ich fände es toll wenn man statt der gesamtanzahl als linearer graph das ganze auch logarisch anzeigen könnten, dort gerne mit Balken für Verdopplung alle X tage Analog zu diesem Chart von world in data: https://ourworldindata.org/coronavirus#trajectories-since-the-100th-confirmed-case

**Comment by silberzwiebel** [comment]
Ist jetzt online (ganz nach unten scrollen): https://codeformuenster.org/COVID-19-NRW/m%C3%BCnster.html
